# Generated by Django 3.2.5 on 2021-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=120)),
                ('price', models.IntegerField(max_length=4)),
                ('sale_start', models.DateField()),
                ('sale_end', models.DateField()),
            ],
        ),
    ]
